#!/bin/sh
uci batch <<-EOF
	set luci.themes.ATMaterial=/luci-static/atmaterial
	set luci.themes.ATMaterial_Red=/luci-static/atmaterial_red
	set luci.themes.ATMaterial_Brown=/luci-static/atmaterial_brown
	commit luci
EOF
exit 0
