#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

get_config() {
	config_get_bool enabled $1 enabled 1
	config_get_bool logger $1 logger
}

start_service() {
	config_load homebox
	config_foreach get_config homebox
	[ $enabled != 1 ] && return 1

	procd_open_instance
	procd_set_param command /usr/bin/homebox
	[ "$logger" == 1 ] && procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "homebox"
}
